name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Print greeting
        run: echo "Hello" 
        shell: powershell
      - name: Print Goodbye
        run: echo "Bye"
        shell: powershell
